### ISSUE TITLE
code comment about some input variables

### ISSUE THREAD

**Issue by Chan-Sun** [RenkunNi/MetaAug#1]
Hi, recently i was reviewing your work about augments for meta learning, very interesting job! 

But some issue arose when i was trying to figure out the mechanism of you code.

Roughly it's about the definition of some input variables. As codes shown below, two pairs of input variables have the same code comment, but i believe they perform differently in your code.
https://github.com/RenkunNi/MetaAug/blob/f5c8a09f7e5e60c491cb4742b4c250782ed16c2f/train_aug.py#L171-L174

https://github.com/RenkunNi/MetaAug/blob/f5c8a09f7e5e60c491cb4742b4c250782ed16c2f/train_aug.py#L185-L188

**Comment by RenkunNi** [comment]
Hi,

Thank you for your interests, I have already updated these two comments for the mentioned input variables. Sorry for the confusing comments. Please let me know if you have any other questions.
